TrabalhofinalAPSOO-Rhauani: processing.IntelFabric Class Reference
processing.IntelFabric Class Reference
Public Member Functions
CPU produceCPU ()
GPU produceGPU ()
Static Public Member Functions
static synchronized IntelFabric getInstance ()
Static Public Attributes
static IntelFabric instance
Private Member Functions
IntelFabric ()
Detailed Description
Author
rhau Concrete fabric -> Intel CPU or GPU
Definition at line 12 of file IntelFabric.java.
Constructor & Destructor Documentation
IntelFabric()
processing.IntelFabric.IntelFabric () private
Definition at line 16 of file IntelFabric.java.
Referenced by processing.IntelFabric.getInstance().
Member Function Documentation
getInstance()
static synchronized IntelFabric processing.IntelFabric.getInstance () static
Definition at line 22 of file IntelFabric.java.
References processing.IntelFabric.instance, and processing.IntelFabric.IntelFabric().
Referenced by entrypoint.environment.ServerEnvironment.createVirtualProcessingUnits(), and entrypoint.environment.DevelopmentEnvironment.createVirtualProcessingUnits().
produceCPU()
CPU processing.IntelFabric.produceCPU ()
Implements processing.ProcessingUnitFabric.
Definition at line 27 of file IntelFabric.java.
produceGPU()
GPU processing.IntelFabric.produceGPU ()
Implements processing.ProcessingUnitFabric.
Definition at line 32 of file IntelFabric.java.
Member Data Documentation
instance
IntelFabric processing.IntelFabric.instance static
Definition at line 14 of file IntelFabric.java.
Referenced by processing.IntelFabric.getInstance().
The documentation for this class was generated from the following file:
src/processing/IntelFabric.java