TrabalhofinalAPSOO-Rhauani: visualization.StatusWindow Class Reference
visualization.StatusWindow Class Reference
Public Member Functions
StatusWindow (ConcreteWindow window)
void draw ()
Public Member Functions inherited from visualization.AbstractWindow
AbstractWindow (ConcreteWindow window)
void drawWindow (String title, String body)
void drawOption (String label, Boolean defaultValue)
Additional Inherited Members
Protected Attributes inherited from visualization.AbstractWindow
ConcreteWindow window
Detailed Description
Author
rhau Status window for all OS
Definition at line 7 of file StatusWindow.java.
Constructor & Destructor Documentation
StatusWindow()
visualization.StatusWindow.StatusWindow (ConcreteWindow window)
Parameters
window
Definition at line 12 of file StatusWindow.java.
References visualization.StatusWindow.draw(), and visualization.AbstractWindow.window.
Member Function Documentation
draw()
void visualization.StatusWindow.draw ()
Reimplemented from visualization.AbstractWindow.
Definition at line 18 of file StatusWindow.java.
References visualization.AbstractWindow.drawWindow().
Referenced by visualization.StatusWindow.StatusWindow().
The documentation for this class was generated from the following file:
src/visualization/StatusWindow.java