TrabalhofinalAPSOO-Rhauani: visualization.ConfigurationWindow Class Reference
visualization.ConfigurationWindow Class Reference
Public Member Functions
ConfigurationWindow (ConcreteWindow window)
void draw ()
Public Member Functions inherited from visualization.AbstractWindow
AbstractWindow (ConcreteWindow window)
void drawWindow (String title, String body)
void drawOption (String label, Boolean defaultValue)
Additional Inherited Members
Protected Attributes inherited from visualization.AbstractWindow
ConcreteWindow window
Detailed Description
Author
rhau Configuration window for all OS
Definition at line 7 of file ConfigurationWindow.java.
Constructor & Destructor Documentation
ConfigurationWindow()
visualization.ConfigurationWindow.ConfigurationWindow (ConcreteWindow window)
Parameters
window
Definition at line 12 of file ConfigurationWindow.java.
References visualization.ConfigurationWindow.draw(), and visualization.AbstractWindow.window.
Member Function Documentation
draw()
void visualization.ConfigurationWindow.draw ()
Reimplemented from visualization.AbstractWindow.
Definition at line 18 of file ConfigurationWindow.java.
References visualization.AbstractWindow.drawOption().
Referenced by visualization.ConfigurationWindow.ConfigurationWindow().
The documentation for this class was generated from the following file:
src/visualization/ConfigurationWindow.java