TrabalhofinalAPSOO-Rhauani: entrypoint.environment.ServerEnvironment Class Reference
entrypoint.environment.ServerEnvironment Class Reference
Public Member Functions
void startSystem ()
void createSystemInterface ()
void createFileSystem ()
void createOperatingSystem ()
void createVirtualProcessingUnits ()
Public Member Functions inherited from entrypoint.SystemFacade
void insertFile (String filename)
AbstractWindow getSystemInterface ()
void setSystemInterface (AbstractWindow systemInterface)
FileComposite getFileSystem ()
void setFileSystem (FileComposite fileSystem)
OperatingSystem getOperatingSystem ()
void setOperatingSystem (OperatingSystem operatingSystem)
CPU getCpuComponent ()
void setCpuComponent (CPU cpuComponent)
GPU getGpuComponent ()
void setGpuComponent (GPU gpuComponent)
String toString ()
Detailed Description
Author
rhau Config for server env
Definition at line 16 of file ServerEnvironment.java.
Member Function Documentation
createFileSystem()
void entrypoint.environment.ServerEnvironment.createFileSystem ()
Reimplemented from entrypoint.SystemFacade.
Definition at line 32 of file ServerEnvironment.java.
References entrypoint.SystemFacade.getFileSystem(), and entrypoint.SystemFacade.setFileSystem().
Referenced by entrypoint.environment.ServerEnvironment.startSystem().
createOperatingSystem()
void entrypoint.environment.ServerEnvironment.createOperatingSystem ()
Reimplemented from entrypoint.SystemFacade.
Definition at line 38 of file ServerEnvironment.java.
References operational.OperatingSystemFabric.createOperatingSystem(), entrypoint.SystemFacade.getOperatingSystem(), entrypoint.SystemFacade.setOperatingSystem(), and operational.systems.OperatingSystem.showSystemInfo().
Referenced by entrypoint.environment.ServerEnvironment.startSystem().
createSystemInterface()
void entrypoint.environment.ServerEnvironment.createSystemInterface ()
Reimplemented from entrypoint.SystemFacade.
Definition at line 27 of file ServerEnvironment.java.
References entrypoint.SystemFacade.setSystemInterface().
Referenced by entrypoint.environment.ServerEnvironment.startSystem().
createVirtualProcessingUnits()
void entrypoint.environment.ServerEnvironment.createVirtualProcessingUnits ()
Reimplemented from entrypoint.SystemFacade.
Definition at line 45 of file ServerEnvironment.java.
References entrypoint.SystemFacade.getCpuComponent(), entrypoint.SystemFacade.getGpuComponent(), processing.IntelFabric.getInstance(), processing.ProcessingUnitFabric.produceCPU(), processing.ProcessingUnitFabric.produceGPU(), entrypoint.SystemFacade.setCpuComponent(), and entrypoint.SystemFacade.setGpuComponent().
Referenced by entrypoint.environment.ServerEnvironment.startSystem().
startSystem()
void entrypoint.environment.ServerEnvironment.startSystem ()
Reimplemented from entrypoint.SystemFacade.
Definition at line 19 of file ServerEnvironment.java.
References entrypoint.environment.ServerEnvironment.createFileSystem(), entrypoint.environment.ServerEnvironment.createOperatingSystem(), entrypoint.environment.ServerEnvironment.createSystemInterface(), and entrypoint.environment.ServerEnvironment.createVirtualProcessingUnits().
The documentation for this class was generated from the following file:
src/entrypoint/environment/ServerEnvironment.java