TrabalhofinalAPSOO-Rhauani: visualization.AbstractWindow Class Reference
visualization.AbstractWindow Class Reference abstract
Public Member Functions
AbstractWindow (ConcreteWindow window)
void drawWindow (String title, String body)
void drawOption (String label, Boolean defaultValue)
abstract void draw ()
Protected Attributes
ConcreteWindow window
Detailed Description
Author
rhau Abstract window superclass
Definition at line 7 of file AbstractWindow.java.
Constructor & Destructor Documentation
AbstractWindow()
visualization.AbstractWindow.AbstractWindow (ConcreteWindow window)
Definition at line 11 of file AbstractWindow.java.
References visualization.AbstractWindow.window.
Member Function Documentation
draw()
abstract void visualization.AbstractWindow.draw () abstract
Reimplemented in visualization.ConfigurationWindow, visualization.StartupWindow, and visualization.StatusWindow.
drawOption()
void visualization.AbstractWindow.drawOption (String label, Boolean defaultValue)
Definition at line 19 of file AbstractWindow.java.
References visualization.ConcreteWindow.drawOption().
Referenced by visualization.ConfigurationWindow.draw().
drawWindow()
void visualization.AbstractWindow.drawWindow (String title, String body)
Definition at line 15 of file AbstractWindow.java.
References visualization.ConcreteWindow.drawWindow().
Referenced by visualization.StartupWindow.draw(), and visualization.StatusWindow.draw().
Member Data Documentation
window
ConcreteWindow visualization.AbstractWindow.window protected
Definition at line 9 of file AbstractWindow.java.
Referenced by visualization.AbstractWindow.AbstractWindow(), visualization.ConfigurationWindow.ConfigurationWindow(), visualization.StartupWindow.StartupWindow(), and visualization.StatusWindow.StatusWindow().
The documentation for this class was generated from the following file:
src/visualization/AbstractWindow.java