TrabalhofinalAPSOO-Rhauani: entrypoint.environment.UserEnvironment Class Reference
entrypoint.environment.UserEnvironment Class Reference
Public Member Functions
void startSystem ()
void createSystemInterface ()
void createFileSystem ()
void createOperatingSystem ()
void createVirtualProcessingUnits ()
Public Member Functions inherited from entrypoint.SystemFacade
void insertFile (String filename)
AbstractWindow getSystemInterface ()
void setSystemInterface (AbstractWindow systemInterface)
FileComposite getFileSystem ()
void setFileSystem (FileComposite fileSystem)
OperatingSystem getOperatingSystem ()
void setOperatingSystem (OperatingSystem operatingSystem)
CPU getCpuComponent ()
void setCpuComponent (CPU cpuComponent)
GPU getGpuComponent ()
void setGpuComponent (GPU gpuComponent)
String toString ()
Detailed Description
Author
rhau Config for user env
Definition at line 16 of file UserEnvironment.java.
Member Function Documentation
createFileSystem()
void entrypoint.environment.UserEnvironment.createFileSystem ()
Reimplemented from entrypoint.SystemFacade.
Definition at line 32 of file UserEnvironment.java.
References entrypoint.SystemFacade.getFileSystem(), and entrypoint.SystemFacade.setFileSystem().
Referenced by entrypoint.environment.UserEnvironment.startSystem().
createOperatingSystem()
void entrypoint.environment.UserEnvironment.createOperatingSystem ()
Reimplemented from entrypoint.SystemFacade.
Definition at line 38 of file UserEnvironment.java.
References operational.OperatingSystemFabric.createOperatingSystem(), entrypoint.SystemFacade.getOperatingSystem(), entrypoint.SystemFacade.setOperatingSystem(), and operational.systems.OperatingSystem.showSystemInfo().
Referenced by entrypoint.environment.UserEnvironment.startSystem().
createSystemInterface()
void entrypoint.environment.UserEnvironment.createSystemInterface ()
Reimplemented from entrypoint.SystemFacade.
Definition at line 27 of file UserEnvironment.java.
References entrypoint.SystemFacade.setSystemInterface().
Referenced by entrypoint.environment.UserEnvironment.startSystem().
createVirtualProcessingUnits()
void entrypoint.environment.UserEnvironment.createVirtualProcessingUnits ()
Reimplemented from entrypoint.SystemFacade.
Definition at line 45 of file UserEnvironment.java.
References entrypoint.SystemFacade.getCpuComponent(), entrypoint.SystemFacade.getGpuComponent(), processing.AMDFabric.getInstance(), processing.ProcessingUnitFabric.produceCPU(), processing.ProcessingUnitFabric.produceGPU(), entrypoint.SystemFacade.setCpuComponent(), and entrypoint.SystemFacade.setGpuComponent().
Referenced by entrypoint.environment.UserEnvironment.startSystem().
startSystem()
void entrypoint.environment.UserEnvironment.startSystem ()
Reimplemented from entrypoint.SystemFacade.
Definition at line 19 of file UserEnvironment.java.
References entrypoint.environment.UserEnvironment.createFileSystem(), entrypoint.environment.UserEnvironment.createOperatingSystem(), entrypoint.environment.UserEnvironment.createSystemInterface(), and entrypoint.environment.UserEnvironment.createVirtualProcessingUnits().
The documentation for this class was generated from the following file:
src/entrypoint/environment/UserEnvironment.java