TrabalhofinalAPSOO-Rhauani: main.Client Class Reference
main.Client Class Reference
Static Public Member Functions
static void main (String[] args)
static void dev ()
static void server ()
static void user ()
Detailed Description
Definition at line 8 of file Client.java.
Member Function Documentation
dev()
static void main.Client.dev () static
Definition at line 20 of file Client.java.
References entrypoint.SystemFacade.startSystem().
Referenced by main.Client.main().
main()
static void main.Client.main (String[] args) static
Definition at line 10 of file Client.java.
References main.Client.dev(), main.Client.server(), and main.Client.user().
server()
static void main.Client.server () static
Definition at line 25 of file Client.java.
References entrypoint.SystemFacade.startSystem().
Referenced by main.Client.main().
user()
static void main.Client.user () static
Definition at line 30 of file Client.java.
References entrypoint.SystemFacade.startSystem().
Referenced by main.Client.main().
The documentation for this class was generated from the following file:
src/main/Client.java