TrabalhofinalAPSOO-Rhauani: entrypoint.environment.DevelopmentEnvironment Class Reference
entrypoint.environment.DevelopmentEnvironment Class Reference
Public Member Functions
void startSystem ()
void createSystemInterface ()
void createFileSystem ()
void createOperatingSystem ()
void createVirtualProcessingUnits ()
Public Member Functions inherited from entrypoint.SystemFacade
void insertFile (String filename)
AbstractWindow getSystemInterface ()
void setSystemInterface (AbstractWindow systemInterface)
FileComposite getFileSystem ()
void setFileSystem (FileComposite fileSystem)
OperatingSystem getOperatingSystem ()
void setOperatingSystem (OperatingSystem operatingSystem)
CPU getCpuComponent ()
void setCpuComponent (CPU cpuComponent)
GPU getGpuComponent ()
void setGpuComponent (GPU gpuComponent)
String toString ()
Detailed Description
Author
rhau System config for dev env
Definition at line 17 of file DevelopmentEnvironment.java.
Member Function Documentation
createFileSystem()
void entrypoint.environment.DevelopmentEnvironment.createFileSystem ()
Reimplemented from entrypoint.SystemFacade.
Definition at line 34 of file DevelopmentEnvironment.java.
References entrypoint.SystemFacade.getFileSystem(), and entrypoint.SystemFacade.setFileSystem().
Referenced by entrypoint.environment.DevelopmentEnvironment.startSystem().
createOperatingSystem()
void entrypoint.environment.DevelopmentEnvironment.createOperatingSystem ()
Reimplemented from entrypoint.SystemFacade.
Definition at line 40 of file DevelopmentEnvironment.java.
References operational.OperatingSystemFabric.createOperatingSystem(), entrypoint.SystemFacade.getOperatingSystem(), entrypoint.SystemFacade.setOperatingSystem(), and operational.systems.OperatingSystem.showSystemInfo().
Referenced by entrypoint.environment.DevelopmentEnvironment.startSystem().
createSystemInterface()
void entrypoint.environment.DevelopmentEnvironment.createSystemInterface ()
Reimplemented from entrypoint.SystemFacade.
Definition at line 28 of file DevelopmentEnvironment.java.
References entrypoint.SystemFacade.setSystemInterface().
Referenced by entrypoint.environment.DevelopmentEnvironment.startSystem().
createVirtualProcessingUnits()
void entrypoint.environment.DevelopmentEnvironment.createVirtualProcessingUnits ()
Reimplemented from entrypoint.SystemFacade.
Definition at line 47 of file DevelopmentEnvironment.java.
References entrypoint.SystemFacade.getCpuComponent(), entrypoint.SystemFacade.getGpuComponent(), processing.AMDFabric.getInstance(), processing.IntelFabric.getInstance(), processing.ProcessingUnitFabric.produceCPU(), processing.ProcessingUnitFabric.produceGPU(), entrypoint.SystemFacade.setCpuComponent(), and entrypoint.SystemFacade.setGpuComponent().
Referenced by entrypoint.environment.DevelopmentEnvironment.startSystem().
startSystem()
void entrypoint.environment.DevelopmentEnvironment.startSystem ()
Reimplemented from entrypoint.SystemFacade.
Definition at line 20 of file DevelopmentEnvironment.java.
References entrypoint.environment.DevelopmentEnvironment.createFileSystem(), entrypoint.environment.DevelopmentEnvironment.createOperatingSystem(), entrypoint.environment.DevelopmentEnvironment.createSystemInterface(), and entrypoint.environment.DevelopmentEnvironment.createVirtualProcessingUnits().
The documentation for this class was generated from the following file:
src/entrypoint/environment/DevelopmentEnvironment.java