TrabalhofinalAPSOO-Rhauani: visualization.StartupWindow Class Reference
visualization.StartupWindow Class Reference
Public Member Functions
StartupWindow (ConcreteWindow window)
void draw ()
Public Member Functions inherited from visualization.AbstractWindow
AbstractWindow (ConcreteWindow window)
void drawWindow (String title, String body)
void drawOption (String label, Boolean defaultValue)
Additional Inherited Members
Protected Attributes inherited from visualization.AbstractWindow
ConcreteWindow window
Detailed Description
Author
rhau Startup window for all OS
Definition at line 7 of file StartupWindow.java.
Constructor & Destructor Documentation
StartupWindow()
visualization.StartupWindow.StartupWindow (ConcreteWindow window)
Parameters
window
Definition at line 12 of file StartupWindow.java.
References visualization.StartupWindow.draw(), and visualization.AbstractWindow.window.
Member Function Documentation
draw()
void visualization.StartupWindow.draw ()
Reimplemented from visualization.AbstractWindow.
Definition at line 18 of file StartupWindow.java.
References visualization.AbstractWindow.drawWindow().
Referenced by visualization.StartupWindow.StartupWindow().
The documentation for this class was generated from the following file:
src/visualization/StartupWindow.java