TrabalhofinalAPSOO-Rhauani: operational.systems.Windows Class Reference
operational.systems.Windows Class Reference
Public Member Functions
Windows ()
void showSystemInfo ()
Public Member Functions inherited from operational.systems.OperatingSystem
String getTradeName ()
void setTradeName (String tradeName)
String getVersion ()
void setVersion (String version)
String getAlias ()
void setAlias (String alias)
String toString ()
Detailed Description
Author
rhau Microsoft Windows OS
Definition at line 7 of file Windows.java.
Constructor & Destructor Documentation
Windows()
operational.systems.Windows.Windows ()
Definition at line 9 of file Windows.java.
References operational.systems.OperatingSystem.setAlias(), operational.systems.OperatingSystem.setTradeName(), and operational.systems.OperatingSystem.setVersion().
Member Function Documentation
showSystemInfo()
void operational.systems.Windows.showSystemInfo ()
Reimplemented from operational.systems.OperatingSystem.
Definition at line 16 of file Windows.java.
References operational.systems.OperatingSystem.toString().
The documentation for this class was generated from the following file:
src/operational/systems/Windows.java