TrabalhofinalAPSOO-Rhauani: operational.systems.OperatingSystem Class Reference
operational.systems.OperatingSystem Class Reference abstract
Public Member Functions
abstract void showSystemInfo ()
String getTradeName ()
void setTradeName (String tradeName)
String getVersion ()
void setVersion (String version)
String getAlias ()
void setAlias (String alias)
String toString ()
Private Attributes
String tradeName
String version
String alias
Detailed Description
Author
rhau OS superclass
Definition at line 7 of file OperatingSystem.java.
Member Function Documentation
getAlias()
String operational.systems.OperatingSystem.getAlias ()
Returns
the alias
Definition at line 42 of file OperatingSystem.java.
References operational.systems.OperatingSystem.alias.
getTradeName()
String operational.systems.OperatingSystem.getTradeName ()
Returns
the tradeName
Definition at line 18 of file OperatingSystem.java.
References operational.systems.OperatingSystem.tradeName.
getVersion()
String operational.systems.OperatingSystem.getVersion ()
Returns
the version
Definition at line 30 of file OperatingSystem.java.
References operational.systems.OperatingSystem.version.
setAlias()
void operational.systems.OperatingSystem.setAlias (String alias)
Parameters
alias the alias to set
Definition at line 48 of file OperatingSystem.java.
References operational.systems.OperatingSystem.alias.
Referenced by operational.systems.IOS.IOS(), operational.systems.Ubuntu.Ubuntu(), and operational.systems.Windows.Windows().
setTradeName()
void operational.systems.OperatingSystem.setTradeName (String tradeName)
Parameters
tradeName the tradeName to set
Definition at line 24 of file OperatingSystem.java.
References operational.systems.OperatingSystem.tradeName.
Referenced by operational.systems.IOS.IOS(), operational.systems.Ubuntu.Ubuntu(), and operational.systems.Windows.Windows().
setVersion()
void operational.systems.OperatingSystem.setVersion (String version)
Parameters
version the version to set
Definition at line 36 of file OperatingSystem.java.
References operational.systems.OperatingSystem.version.
Referenced by operational.systems.IOS.IOS(), operational.systems.Ubuntu.Ubuntu(), and operational.systems.Windows.Windows().
showSystemInfo()
abstract void operational.systems.OperatingSystem.showSystemInfo () abstract
Reimplemented in operational.systems.IOS, operational.systems.Ubuntu, and operational.systems.Windows.
Referenced by entrypoint.environment.ServerEnvironment.createOperatingSystem(), entrypoint.environment.UserEnvironment.createOperatingSystem(), and entrypoint.environment.DevelopmentEnvironment.createOperatingSystem().
toString()
String operational.systems.OperatingSystem.toString ()
Definition at line 56 of file OperatingSystem.java.
References operational.systems.OperatingSystem.alias, operational.systems.OperatingSystem.tradeName, and operational.systems.OperatingSystem.version.
Referenced by operational.systems.IOS.showSystemInfo(), operational.systems.Windows.showSystemInfo(), and operational.systems.Ubuntu.showSystemInfo().
Member Data Documentation
alias
String operational.systems.OperatingSystem.alias private
Definition at line 11 of file OperatingSystem.java.
Referenced by operational.systems.OperatingSystem.getAlias(), operational.systems.OperatingSystem.setAlias(), and operational.systems.OperatingSystem.toString().
tradeName
String operational.systems.OperatingSystem.tradeName private
Definition at line 9 of file OperatingSystem.java.
Referenced by operational.systems.OperatingSystem.getTradeName(), operational.systems.OperatingSystem.setTradeName(), and operational.systems.OperatingSystem.toString().
version
String operational.systems.OperatingSystem.version private
Definition at line 10 of file OperatingSystem.java.
Referenced by operational.systems.OperatingSystem.getVersion(), operational.systems.OperatingSystem.setVersion(), and operational.systems.OperatingSystem.toString().
The documentation for this class was generated from the following file:
src/operational/systems/OperatingSystem.java