TrabalhofinalAPSOO-Rhauani: processing.AMDFabric Class Reference
processing.AMDFabric Class Reference
Public Member Functions
CPU produceCPU ()
GPU produceGPU ()
Static Public Member Functions
static synchronized AMDFabric getInstance ()
Static Public Attributes
static AMDFabric instance
Private Member Functions
AMDFabric ()
Detailed Description
Author
rhau Concrete fabric -> AMD CPU or GPU
Definition at line 12 of file AMDFabric.java.
Constructor & Destructor Documentation
AMDFabric()
processing.AMDFabric.AMDFabric () private
Definition at line 16 of file AMDFabric.java.
Referenced by processing.AMDFabric.getInstance().
Member Function Documentation
getInstance()
static synchronized AMDFabric processing.AMDFabric.getInstance () static
Definition at line 22 of file AMDFabric.java.
References processing.AMDFabric.AMDFabric(), and processing.AMDFabric.instance.
Referenced by entrypoint.environment.UserEnvironment.createVirtualProcessingUnits(), and entrypoint.environment.DevelopmentEnvironment.createVirtualProcessingUnits().
produceCPU()
CPU processing.AMDFabric.produceCPU ()
Implements processing.ProcessingUnitFabric.
Definition at line 27 of file AMDFabric.java.
produceGPU()
GPU processing.AMDFabric.produceGPU ()
Implements processing.ProcessingUnitFabric.
Definition at line 32 of file AMDFabric.java.
Member Data Documentation
instance
AMDFabric processing.AMDFabric.instance static
Definition at line 14 of file AMDFabric.java.
Referenced by processing.AMDFabric.getInstance().
The documentation for this class was generated from the following file:
src/processing/AMDFabric.java