TrabalhofinalAPSOO-Rhauani: entrypoint.SystemFacade Class Reference
entrypoint.SystemFacade Class Reference abstract
Public Member Functions
abstract void startSystem ()
abstract void createSystemInterface ()
abstract void createFileSystem ()
abstract void createOperatingSystem ()
abstract void createVirtualProcessingUnits ()
void insertFile (String filename)
AbstractWindow getSystemInterface ()
void setSystemInterface (AbstractWindow systemInterface)
FileComposite getFileSystem ()
void setFileSystem (FileComposite fileSystem)
OperatingSystem getOperatingSystem ()
void setOperatingSystem (OperatingSystem operatingSystem)
CPU getCpuComponent ()
void setCpuComponent (CPU cpuComponent)
GPU getGpuComponent ()
void setGpuComponent (GPU gpuComponent)
String toString ()
Private Attributes
AbstractWindow systemInterface
FileComposite fileSystem
OperatingSystem operatingSystem
CPU cpuComponent
GPU gpuComponent
Detailed Description
Author
rhau System facade superclass
Definition at line 14 of file SystemFacade.java.
Member Function Documentation
createFileSystem()
abstract void entrypoint.SystemFacade.createFileSystem () abstract
Reimplemented in entrypoint.environment.DevelopmentEnvironment, entrypoint.environment.ServerEnvironment, and entrypoint.environment.UserEnvironment.
createOperatingSystem()
abstract void entrypoint.SystemFacade.createOperatingSystem () abstract
Reimplemented in entrypoint.environment.DevelopmentEnvironment, entrypoint.environment.ServerEnvironment, and entrypoint.environment.UserEnvironment.
createSystemInterface()
abstract void entrypoint.SystemFacade.createSystemInterface () abstract
Reimplemented in entrypoint.environment.DevelopmentEnvironment, entrypoint.environment.ServerEnvironment, and entrypoint.environment.UserEnvironment.
createVirtualProcessingUnits()
abstract void entrypoint.SystemFacade.createVirtualProcessingUnits () abstract
Reimplemented in entrypoint.environment.DevelopmentEnvironment, entrypoint.environment.ServerEnvironment, and entrypoint.environment.UserEnvironment.
getCpuComponent()
CPU entrypoint.SystemFacade.getCpuComponent ()
Returns
the cpuComponent
Definition at line 71 of file SystemFacade.java.
References entrypoint.SystemFacade.cpuComponent.
Referenced by entrypoint.environment.ServerEnvironment.createVirtualProcessingUnits(), entrypoint.environment.UserEnvironment.createVirtualProcessingUnits(), and entrypoint.environment.DevelopmentEnvironment.createVirtualProcessingUnits().
getFileSystem()
FileComposite entrypoint.SystemFacade.getFileSystem ()
Returns
the fileSystem
Definition at line 47 of file SystemFacade.java.
References entrypoint.SystemFacade.fileSystem.
Referenced by entrypoint.environment.ServerEnvironment.createFileSystem(), entrypoint.environment.UserEnvironment.createFileSystem(), entrypoint.environment.DevelopmentEnvironment.createFileSystem(), and entrypoint.SystemFacade.insertFile().
getGpuComponent()
GPU entrypoint.SystemFacade.getGpuComponent ()
Returns
the gpuComponent
Definition at line 83 of file SystemFacade.java.
References entrypoint.SystemFacade.gpuComponent.
Referenced by entrypoint.environment.ServerEnvironment.createVirtualProcessingUnits(), entrypoint.environment.UserEnvironment.createVirtualProcessingUnits(), and entrypoint.environment.DevelopmentEnvironment.createVirtualProcessingUnits().
getOperatingSystem()
OperatingSystem entrypoint.SystemFacade.getOperatingSystem ()
Returns
the operationalSystem
Definition at line 59 of file SystemFacade.java.
References entrypoint.SystemFacade.operatingSystem.
Referenced by entrypoint.environment.ServerEnvironment.createOperatingSystem(), entrypoint.environment.UserEnvironment.createOperatingSystem(), and entrypoint.environment.DevelopmentEnvironment.createOperatingSystem().
getSystemInterface()
AbstractWindow entrypoint.SystemFacade.getSystemInterface ()
Returns
the systemInterface
Definition at line 35 of file SystemFacade.java.
References entrypoint.SystemFacade.systemInterface.
insertFile()
void entrypoint.SystemFacade.insertFile (String filename)
Definition at line 28 of file SystemFacade.java.
References storage.FileComposite.addFile(), and entrypoint.SystemFacade.getFileSystem().
setCpuComponent()
void entrypoint.SystemFacade.setCpuComponent (CPU cpuComponent)
Parameters
cpuComponent the cpuComponent to set
Definition at line 77 of file SystemFacade.java.
References entrypoint.SystemFacade.cpuComponent.
Referenced by entrypoint.environment.ServerEnvironment.createVirtualProcessingUnits(), entrypoint.environment.UserEnvironment.createVirtualProcessingUnits(), and entrypoint.environment.DevelopmentEnvironment.createVirtualProcessingUnits().
setFileSystem()
void entrypoint.SystemFacade.setFileSystem (FileComposite fileSystem)
Parameters
fileSystem the fileSystem to set
Definition at line 53 of file SystemFacade.java.
References entrypoint.SystemFacade.fileSystem.
Referenced by entrypoint.environment.ServerEnvironment.createFileSystem(), entrypoint.environment.UserEnvironment.createFileSystem(), and entrypoint.environment.DevelopmentEnvironment.createFileSystem().
setGpuComponent()
void entrypoint.SystemFacade.setGpuComponent (GPU gpuComponent)
Parameters
gpuComponent the gpuComponent to set
Definition at line 89 of file SystemFacade.java.
References entrypoint.SystemFacade.gpuComponent.
Referenced by entrypoint.environment.ServerEnvironment.createVirtualProcessingUnits(), entrypoint.environment.UserEnvironment.createVirtualProcessingUnits(), and entrypoint.environment.DevelopmentEnvironment.createVirtualProcessingUnits().
setOperatingSystem()
void entrypoint.SystemFacade.setOperatingSystem (OperatingSystem operatingSystem)
Parameters
operatingSystem the operationalSystem to set
Definition at line 65 of file SystemFacade.java.
References entrypoint.SystemFacade.operatingSystem.
Referenced by entrypoint.environment.ServerEnvironment.createOperatingSystem(), entrypoint.environment.UserEnvironment.createOperatingSystem(), and entrypoint.environment.DevelopmentEnvironment.createOperatingSystem().
setSystemInterface()
void entrypoint.SystemFacade.setSystemInterface (AbstractWindow systemInterface)
Parameters
systemInterface the systemInterface to set
Definition at line 41 of file SystemFacade.java.
References entrypoint.SystemFacade.systemInterface.
Referenced by entrypoint.environment.ServerEnvironment.createSystemInterface(), entrypoint.environment.UserEnvironment.createSystemInterface(), and entrypoint.environment.DevelopmentEnvironment.createSystemInterface().
startSystem()
abstract void entrypoint.SystemFacade.startSystem () abstract
Reimplemented in entrypoint.environment.DevelopmentEnvironment, entrypoint.environment.ServerEnvironment, and entrypoint.environment.UserEnvironment.
Referenced by main.Client.dev(), main.Client.server(), and main.Client.user().
toString()
String entrypoint.SystemFacade.toString ()
Definition at line 96 of file SystemFacade.java.
References entrypoint.SystemFacade.cpuComponent, entrypoint.SystemFacade.fileSystem, entrypoint.SystemFacade.gpuComponent, entrypoint.SystemFacade.operatingSystem, and entrypoint.SystemFacade.systemInterface.
Member Data Documentation
cpuComponent
CPU entrypoint.SystemFacade.cpuComponent private
Definition at line 19 of file SystemFacade.java.
Referenced by entrypoint.SystemFacade.getCpuComponent(), entrypoint.SystemFacade.setCpuComponent(), and entrypoint.SystemFacade.toString().
fileSystem
FileComposite entrypoint.SystemFacade.fileSystem private
Definition at line 17 of file SystemFacade.java.
Referenced by entrypoint.SystemFacade.getFileSystem(), entrypoint.SystemFacade.setFileSystem(), and entrypoint.SystemFacade.toString().
gpuComponent
GPU entrypoint.SystemFacade.gpuComponent private
Definition at line 20 of file SystemFacade.java.
Referenced by entrypoint.SystemFacade.getGpuComponent(), entrypoint.SystemFacade.setGpuComponent(), and entrypoint.SystemFacade.toString().
operatingSystem
OperatingSystem entrypoint.SystemFacade.operatingSystem private
Definition at line 18 of file SystemFacade.java.
Referenced by entrypoint.SystemFacade.getOperatingSystem(), entrypoint.SystemFacade.setOperatingSystem(), and entrypoint.SystemFacade.toString().
systemInterface
AbstractWindow entrypoint.SystemFacade.systemInterface private
Definition at line 16 of file SystemFacade.java.
Referenced by entrypoint.SystemFacade.getSystemInterface(), entrypoint.SystemFacade.setSystemInterface(), and entrypoint.SystemFacade.toString().
The documentation for this class was generated from the following file:
src/entrypoint/SystemFacade.java