TrabalhofinalAPSOO-Rhauani: storage.FileComposite Class Reference
storage.FileComposite Class Reference
Public Member Functions
FileComposite (String filename)
void printFilename ()
void addFile (FileComponent newFile)
void removeFile (String filename) throws Exception
FileComponent getFile (String filename) throws Exception
ArrayList< FileComponent > getFiles ()
String toString ()
Public Member Functions inherited from storage.types.FileComponent
FileComponent (String filename)
String getFilename ()
Private Attributes
ArrayList< FileComponent > files = new ArrayList<>()
Detailed Description
Author
rhau Base file system
Definition at line 11 of file FileComposite.java.
Constructor & Destructor Documentation
FileComposite()
storage.FileComposite.FileComposite (String filename)
Parameters
filename
Definition at line 18 of file FileComposite.java.
References storage.types.FileComponent.filename.
Member Function Documentation
addFile()
void storage.FileComposite.addFile (FileComponent newFile)
Reimplemented from storage.types.FileComponent.
Definition at line 31 of file FileComposite.java.
Referenced by entrypoint.SystemFacade.insertFile().
getFile()
FileComponent storage.FileComposite.getFile (String filename) throws Exception
Reimplemented from storage.types.FileComponent.
Definition at line 47 of file FileComposite.java.
References storage.types.FileComponent.filename, and storage.FileComposite.files.
getFiles()
ArrayList<FileComponent> storage.FileComposite.getFiles ()
Returns
the files
Definition at line 59 of file FileComposite.java.
References storage.FileComposite.files.
printFilename()
void storage.FileComposite.printFilename ()
Reimplemented from storage.types.FileComponent.
Definition at line 23 of file FileComposite.java.
References storage.FileComposite.files, and storage.types.FileComponent.getFilename().
removeFile()
void storage.FileComposite.removeFile (String filename) throws Exception
Reimplemented from storage.types.FileComponent.
Definition at line 36 of file FileComposite.java.
References storage.types.FileComponent.filename, and storage.FileComposite.files.
toString()
String storage.FileComposite.toString ()
Reimplemented from storage.types.FileComponent.
Definition at line 67 of file FileComposite.java.
References storage.FileComposite.files.
Member Data Documentation
files
ArrayList<FileComponent> storage.FileComposite.files = new ArrayList<>() private
Definition at line 13 of file FileComposite.java.
Referenced by storage.FileComposite.getFile(), storage.FileComposite.getFiles(), storage.FileComposite.printFilename(), storage.FileComposite.removeFile(), and storage.FileComposite.toString().
The documentation for this class was generated from the following file:
src/storage/FileComposite.java