TrabalhofinalAPSOO-Rhauani: processing.units.ClockInterval Class Reference
processing.units.ClockInterval Class Reference
Public Member Functions
ClockInterval (Double baseClock, Double turboClock)
Double getBaseClock ()
void setBaseClock (Double baseClock)
Double getTurboClock ()
void setTurboClock (Double turboClock)
String toString ()
Private Attributes
Double baseClock
Double turboClock
Detailed Description
Author
rhau Base and turbo clock for CPU and GPU
Definition at line 7 of file ClockInterval.java.
Constructor & Destructor Documentation
ClockInterval()
processing.units.ClockInterval.ClockInterval (Double baseClock, Double turboClock)
Parameters
baseClock
turboClock
Definition at line 16 of file ClockInterval.java.
References processing.units.ClockInterval.baseClock, and processing.units.ClockInterval.turboClock.
Member Function Documentation
getBaseClock()
Double processing.units.ClockInterval.getBaseClock ()
Returns
the baseClock
Definition at line 23 of file ClockInterval.java.
References processing.units.ClockInterval.baseClock.
Referenced by processing.units.ClockInterval.toString().
getTurboClock()
Double processing.units.ClockInterval.getTurboClock ()
Returns
the turboClock
Definition at line 35 of file ClockInterval.java.
References processing.units.ClockInterval.turboClock.
Referenced by processing.units.ClockInterval.toString().
setBaseClock()
void processing.units.ClockInterval.setBaseClock (Double baseClock)
Parameters
baseClock the baseClock to set
Definition at line 29 of file ClockInterval.java.
References processing.units.ClockInterval.baseClock.
setTurboClock()
void processing.units.ClockInterval.setTurboClock (Double turboClock)
Parameters
turboClock the turboClock to set
Definition at line 41 of file ClockInterval.java.
References processing.units.ClockInterval.turboClock.
toString()
String processing.units.ClockInterval.toString ()
Definition at line 48 of file ClockInterval.java.
References processing.units.ClockInterval.baseClock, processing.units.ClockInterval.getBaseClock(), processing.units.ClockInterval.getTurboClock(), and processing.units.ClockInterval.turboClock.
Referenced by processing.units.GPU.toString().
Member Data Documentation
baseClock
Double processing.units.ClockInterval.baseClock private
Definition at line 9 of file ClockInterval.java.
Referenced by processing.units.ClockInterval.ClockInterval(), processing.units.ClockInterval.getBaseClock(), processing.units.ClockInterval.setBaseClock(), and processing.units.ClockInterval.toString().
turboClock
Double processing.units.ClockInterval.turboClock private
Definition at line 10 of file ClockInterval.java.
Referenced by processing.units.ClockInterval.ClockInterval(), processing.units.ClockInterval.getTurboClock(), processing.units.ClockInterval.setTurboClock(), and processing.units.ClockInterval.toString().
The documentation for this class was generated from the following file:
src/processing/units/ClockInterval.java