TrabalhofinalAPSOO-Rhauani: operational.OperatingSystemFabric Interface Reference
operational.OperatingSystemFabric Interface Reference
Public Member Functions
OperatingSystem createOperatingSystem ()
Detailed Description
Author
rhau OS fabric interface
Definition at line 9 of file OperatingSystemFabric.java.
Member Function Documentation
createOperatingSystem()
OperatingSystem operational.OperatingSystemFabric.createOperatingSystem ()
Implemented in operational.AppleFabric, operational.LinuxFabric, and operational.WindowsFabric.
Referenced by entrypoint.environment.ServerEnvironment.createOperatingSystem(), entrypoint.environment.UserEnvironment.createOperatingSystem(), and entrypoint.environment.DevelopmentEnvironment.createOperatingSystem().
The documentation for this interface was generated from the following file:
src/operational/OperatingSystemFabric.java