TrabalhofinalAPSOO-Rhauani: processing.ProcessingUnitFabric Interface Reference
processing.ProcessingUnitFabric Interface Reference
Public Member Functions
CPU produceCPU ()
GPU produceGPU ()
Detailed Description
Author
rhau Abstract factory 'ProcessingUnit' -> CPU or GPU
Definition at line 10 of file ProcessingUnitFabric.java.
Member Function Documentation
produceCPU()
CPU processing.ProcessingUnitFabric.produceCPU ()
Implemented in processing.AMDFabric, and processing.IntelFabric.
Referenced by entrypoint.environment.ServerEnvironment.createVirtualProcessingUnits(), entrypoint.environment.UserEnvironment.createVirtualProcessingUnits(), and entrypoint.environment.DevelopmentEnvironment.createVirtualProcessingUnits().
produceGPU()
GPU processing.ProcessingUnitFabric.produceGPU ()
Implemented in processing.AMDFabric, and processing.IntelFabric.
Referenced by entrypoint.environment.ServerEnvironment.createVirtualProcessingUnits(), entrypoint.environment.UserEnvironment.createVirtualProcessingUnits(), and entrypoint.environment.DevelopmentEnvironment.createVirtualProcessingUnits().
The documentation for this interface was generated from the following file:
src/processing/ProcessingUnitFabric.java